steps:
  # Step 1: Build the Docker image using the Dockerfile in the current directory
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Image'
    args: 
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/upgradlabs-1749732690621/bookmyshow-repo/frontend:v1'
      - '.'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Image'
    args: 
      - 'push'
      - 'us-east1-docker.pkg.dev/upgradlabs-1749732690621/bookmyshow-repo/frontend:v1'

# The images field automatically handles the push and shows the artifact in the build summary
images:
  - 'us-east1-docker.pkg.dev/upgradlabs-1749732690621/bookmyshow-repo/frontend:v1'

# Optional: Add logging to help with troubleshooting in the Console
options:
  logging: CLOUD_LOGGING_ONLY


